apiVersion: v1 
kind: Service
metadata:
  name: db # worker app expects postgres database to be db
  labels:
    name: postgres-service # can be any name
    app: demo-voting-app
spec:
  ports:
  - port: 5432 # port for postgres db to run
    targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app