apiVersion: v1 
kind: Service # external service 1 - voting app, external service 2 - result app
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer # default is ClusterIP if no type is set, NodePort is used to expose external facing app
  ports:
  - port: 80 # frontend ap that runs on port 80 # this is a service port
    targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app